FROM node:18-alpine

RUN apk add --no-cache sqlite sqlite-dev
WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/src/database/init.sql /init/init.sql
COPY backend/src/database/init_db.sh /usr/local/bin/init_db.sh
RUN chmod +x /usr/local/bin/init_db.sh
COPY backend/ ./
RUN npm run build


EXPOSE 3001

CMD ["npm", "start"]
